### ISSUE TITLE
AES CTR 128 is non standard

### ISSUE THREAD

**Issue by momerm** [milagro-crypto/milagro-crypto-js#31]
The output of AES-CTR-128 differs from other implementations such as the one here http://www.cryptogrium.com/aes-ctr.html.

For example one of the outputs is:

"KEY" : "0700d603a1c514e46b6191ba430a3a0c"
"IV" : "aad1583cd91365e3bb2f0c3430d065bb"
"PLAINTEXT" : "068b25c7bfb1f8bdd4cfc908f69dffc5ddc726a197f0e5f720f730393279be91"
"CIPHERTEXT" : "3f9f9018ddbab7aed09e6fdc54dd24a75c552cbdc593130a6a774802cf0ede58"

The ciphertext is supposed to be:

"CIPHERTEXT" : "3f9f9018ddbab7aed09e6fdc54dd24a71996024d50e2eb86d14509c69d654d5d"

**Comment by mcarrickscott** [comment]
It depends on how the “counting” is done, and this isn’t specified in the
standard.

The counting is done by the function increment(). To change this to get the
same as that website you reference, simply change the order of the for
loop, from 0 up to 15, to 15 down to 0, that is change it to

for (i = 15;i >= 0;i—)

Mike

**Comment by momerm** [comment]
Thank you for the quick response. This has fixed my problem.
