### ISSUE TITLE
Licensing of this library

### ISSUE THREAD

**Issue by Mikerah** [milagro-crypto/milagro-crypto-js#46]
This repository is said to be under the Apache 2 license. However, it was brought up in another issue in another repository (https://github.com/ethereum/eth2.0-pm/issues/13) that it uses code from a GMP-licensed codebase. If this is indeed the case, then this library should be licensed under a GPL license.

**Comment by mcarrickscott** [comment]
This is not the case. Milagro-crypto does not use any GMP code.

Mike

**Comment by Mikerah** [comment]
Resolved.
